import { createContext } from 'react';
export const LanguageContext = createContext();

export const dict = {
  en: {
    dashboard: 'Dashboard', searchItems: 'Search Items', missingItem: 'Missing Item & College Info', messages: 'Messages',
    adminPanel: 'ADMIN PANEL', analytics: 'Analytics', manageUsers: 'Manage Users', manageReports: 'Manage Reports', auditLogs: 'Audit Logs',
    profile: 'Profile', logout: 'Logout', searchAnything: 'Search anything...', notifications: 'Notifications', infoOnly: 'Information Only',
    recentlyReported: 'Recently Reported', welcomeBack: 'Welcome back, here are the recent items in the network.', searchResults: 'Search Results',
    all: 'All', lostItems: 'Lost Items', foundItems: 'Found Items', recentlyInfo: 'Recently Information', noItemsFound: 'No items found',
    contactReporter: 'Contact Reporter', myReports: 'My Reports', languageSettings: 'Language Settings', english: 'English', malay: 'Bahasa Melayu',
    logoutConfirm: 'Log Out?', logoutMsg: 'Are you sure you want to log out of the system?', cancel: 'Cancel', searchName: 'Search name...',
    reportTitle: 'College Missing Item & Information Report', reportTypeField: 'Report Type', typeLost: 'I lost something', typeFound: 'I found something',
    typeInfo: 'For information only', typeOthers: 'Others', itemName: 'Item Name', itemNamePlaceholder: 'e.g. Blue Backpack', date: 'Date', location: 'Location',
    locationPlaceholder: 'Where was it?', description: 'Description', descriptionPlaceholder: 'Provide more details to help identify the item...',
    photo: 'Photo', photoUpload: 'Click to upload or drag and drop image', submitReport: 'Submit Report',
    // Login & Landing page keys
    loginTitle: 'Login', loginWelcome: 'Welcome to Dashboard Adtec Melaka.', emailLabel: 'Email', passwordLabel: 'Password',
    forgotPassword: 'Forgot Password?', signInBtn: 'Sign In', noAccount: 'Don\'t have an account?', signUpBtn: 'Sign Up',
    featuresTab: 'Features', statsTab: 'Stats', howToTab: 'How to Use', loginBtn: 'Login', heroBadge: 'Adtec Melaka Official Platform',
    heroTitle: 'Information Dashboard', heroSubtitle: 'Lost & found management, college information, and student communication in one modern and secure platform.',
    startNow: 'Start Now', learnMore: 'Learn More',
    // Forgot Password keys
    forgotTitle: 'Forgot Password', forgotDesc: 'Enter your email and we will send a link to reset your password.', sendLinkBtn: 'Send Link', linkSentTitle: 'Link Sent!', linkSentDesc: 'Please check your email inbox for further instructions.', backToLoginBtn: 'Back to Login',
    // Signup keys
    signupTitle: 'Create Account', signupDesc: 'Join the Adtec Melaka network.', fullNameLabel: 'Full Name', alreadyAccount: 'Already have an account?', confirmPasswordLabel: 'Confirm Password', passwordMismatchError: 'Passwords do not match', backToHome: 'Back to Home', passwordShortError: 'Password must be at least 8 characters',
    // New keys
    staySignedIn: 'Stay signed in', loading: 'Loading...', loginFailed: 'Login failed. Please ensure email and password are correct.',
    analyticsOverview: 'Analytics Overview', monitorStats: 'Monitor your system statistics directly from the database.', totalUsers: 'Total Users', totalReports: 'Total Reports', resolutionRate: 'Resolution Rate', activeAccounts: 'Active Accounts', systemAuditLogs: 'System Audit Logs', adminActionRecords: 'Admin and system action records.', exportLogs: 'Export Logs', action: 'Action', userEmail: 'User Email', time: 'Time', noLogRecords: 'No log records at the moment. (Please add \'audit_logs\' table)',
    noConversations: 'No conversations.', selectConversation: 'Select a conversation to start messaging', online: 'Online', reportUser: 'Report User', reportType: 'Report Type', spam: 'Spam', scammer: 'Scammer', inappropriate: 'Inappropriate Content', harassment: 'Harassment', typeReason: 'Type reason...', submit: 'Submit', send: 'Send', justNow: 'Just now',
    noInfoYet: 'No announcements yet.', noReportsYet: 'No lost/found reports yet.', newReport: 'New Report:', noNewNotifications: 'No new notifications.',
    myProfile: 'My Profile', nameLabel: 'Name', roleLabel: 'Role', memberSince: 'Member since', loadingReports: 'Loading reports...', noReportsMade: 'You haven\'t reported any items yet.', saving: 'Saving...', messagingComingSoon: 'Messaging system coming soon!',
    alertFillRequired: 'Please fill in the required fields (Name, Date, Location).', alertFillInfo: 'Please fill in the date and description for this info.', defaultInfoTitle: 'Information', defaultLocation: 'General', alertSuccessAdd: 'Successfully added!', alertFailedAdd: 'Failed to add data: ',
    badgeLost: 'Lost', badgeFound: 'Found', badgeInfo: 'Info', normalUser: 'Normal User', today: 'Today', messageFrom: 'Message from', deleteBtn: 'Delete', cannotContactSelf: 'You cannot contact yourself.', confirmResolveReport: 'Are you sure you want to mark this report as Resolved?', markResolved: 'Resolve',
    accountSuspended: 'Your account has been suspended by the Admin.',
    alertInvalidFile: 'Please upload image files only.', alertFileSize: 'File size exceeds 5MB limit.', alertSuccessDelete: 'Successfully deleted!', alertFailedDelete: 'Failed to delete: ', confirmDelete: 'Are you sure you want to delete this item?', confirmDeleteUser: 'Are you sure you want to delete this user?', alertFailedUpdateRole: 'Failed to update role: ', alertFailedSuspend: 'Failed to suspend/activate user: ', alertFailedUpdateStatus: 'Failed to update status: ', alertSuccessReport: 'Report submitted successfully.', alertFailedReport: 'Failed to submit report: ', alertFailedUpload: 'Failed to upload image: ', alertFailedSendMsg: 'Failed to send message: ', alertOtpSent: 'Please check your email for the OTP code.',
    userManagementTitle: 'User Management', userManagementDesc: 'Manage registered users and their roles.', total: 'Total', searchByName: 'Search by name...', status: 'Status', actions: 'Actions', noUsersFound: 'No users found.', changeRole: 'Change Role', activate: 'Activate', suspend: 'Suspend', reportManagementTitle: 'Report Management', reportManagementDesc: 'Approve, reject, or resolve user reports.', reportDetails: 'Report Details', noReportsFound: 'No reports found.', approve: 'Approve', reject: 'Reject', resolve: 'Resolve', viewImage: 'View Image', pending: 'Pending', approved: 'Approved', rejected: 'Rejected', resolved: 'Resolved', overlayWelcomeTitle: 'Welcome Back!', overlayWelcomeDesc: 'To keep connected with us please login with your personal info', overlayHelloTitle: 'Hello, Adtec Student!', overlayHelloDesc: 'Enter your personal details and start your journey with us',
    uploadScreenshot: 'Upload Screenshot / Proof', screenshotNotice: 'Please upload a screenshot proof so admin can verify this report and prevent false reports.', viewProof: 'View Proof', noProofProvided: 'No screenshot provided', proofModalTitle: 'Report Proof Screenshot', screenshotRequired: 'Please upload a screenshot proof before submitting.',
    suspendModalTitle: 'Suspend User Account', suspendDurationLabel: 'Select Suspension Duration', dayCount1: '1 Day', dayCount3: '3 Days', dayCount7: '7 Days', dayCount14: '14 Days', dayCount30: '30 Days', customDays: 'Custom Days', indefinite: 'Permanent (Indefinite)', suspendedUntilDate: 'Suspended until', confirmSuspendBtn: 'Suspend Account',
    logRoleChange: 'Changed user role ({email}) to {role}',
    emailRoleChangeTitle: 'Account Role Updated',
    emailRoleChangeMsg: 'Your ADTEC Dashboard account role has been changed to {role} by the administrator.',
    logUnsuspend: 'Reactivated user account ({email})',
    logSuspendDays: 'Suspended user account ({email}) for {days} days (until {date})',
    logSuspendPermanent: 'Permanently suspended user account ({email})',
    logDeleteUser: 'Permanently deleted user ({email})',
    logReportStatus: 'Changed report status ({email}) to {status}',
    emailAccountActivatedTitle: 'Account Reactivated',
    emailAccountActivatedMsg: 'Good news! Your ADTEC Dashboard account has been reactivated by the administrator. You can now log in normally.',
    emailAccountSuspendedTitle: 'Account Suspension Notice',
    emailAccountSuspendedMsg1: 'Your ADTEC Dashboard account has been suspended by the administrator for violating terms and conditions. ',
    emailAccountSuspendedMsgDays: 'Your account will be suspended for {days} days and can be accessed again after {date}.',
    emailAccountSuspendedMsgPermanent: 'Your account has been PERMANENTLY suspended. Please contact administration if this is a mistake.',
    notifReportStatusTitle: 'Report Status Updated',
    notifReportStatusMsg: 'Your report against {name} is now: {status}.',
    emailReportStatusTitle: 'Your Report Status Has Been Updated',
    emailReportStatusMsg: 'Your report against user {name} has been reviewed by Admin and is now: {status}. Thank you for helping the ADTEC Melaka community.',
    suspendPreviewPermanent: '🔒 Account will be permanently suspended until manually reactivated.',
    suspendPreviewDays: '⏰ Account will be suspended until: {date} (System will automatically unsuspend after period ends)', resetPasswordTitle: 'Set New Password', resetPasswordDesc: 'Please enter your new password below.', resetPasswordSuccess: 'Password successfully changed! You can now login using your new password.', newPasswordLabel: 'New Password', confirmNewPasswordLabel: 'Confirm Password', changePasswordBtn: 'Change Password', invalidLink: 'Invalid or expired link.', sessionNotFound: 'Session not found. Please request a new reset link from the login page.', resetFailed: 'Failed to change password. Please try again.'
  },
  ms: {
    dashboard: 'Papan Pemuka', searchItems: 'Cari Barang', missingItem: 'Barang Hilang & Info Kolej', messages: 'Mesej',
    adminPanel: 'PANEL ADMIN', analytics: 'Analitik', manageUsers: 'Urus Pengguna', manageReports: 'Urus Laporan', auditLogs: 'Log Audit',
    profile: 'Profil', logout: 'Log Keluar', searchAnything: 'Cari apa-apa sahaja...', notifications: 'Notifikasi', infoOnly: 'Maklumat Sahaja',
    recentlyReported: 'Laporan Terkini', welcomeBack: 'Selamat kembali, ini adalah maklumat terkini di dalam rangkaian.', searchResults: 'Hasil Carian',
    all: 'Semua', lostItems: 'Barang Hilang', foundItems: 'Barang Jumpa', recentlyInfo: 'Maklumat Terkini', noItemsFound: 'Tiada item dijumpai',
    contactReporter: 'Hubungi Pelapor', myReports: 'Laporan Saya', languageSettings: 'Tetapan Bahasa', english: 'Bahasa Inggeris', malay: 'Bahasa Melayu',
    logoutConfirm: 'Log Keluar?', logoutMsg: 'Adakah anda pasti ingin log keluar daripada sistem?', cancel: 'Batal', searchName: 'Cari nama...',
    reportTitle: 'Laporan Barang Hilang & Maklumat Kolej', reportTypeField: 'Jenis Laporan', typeLost: 'Saya kehilangan barang', typeFound: 'Saya terjumpa barang',
    typeInfo: 'Untuk maklumat sahaja', typeOthers: 'Lain-lain', itemName: 'Nama Barang', itemNamePlaceholder: 'cth. Beg Galas Biru', date: 'Tarikh', location: 'Lokasi',
    locationPlaceholder: 'Di manakah lokasinya?', description: 'Penerangan', descriptionPlaceholder: 'Berikan maklumat lanjut tentang barang tersebut...',
    photo: 'Gambar', photoUpload: 'Klik untuk muat naik atau letak gambar di sini', submitReport: 'Hantar Laporan',
    // Login & Landing page keys
    loginTitle: 'Log Masuk', loginWelcome: 'Selamat datang ke Dashboard Adtec Melaka.', emailLabel: 'E-mel', passwordLabel: 'Kata Laluan',
    forgotPassword: 'Lupa Kata Laluan?', signInBtn: 'Log Masuk', noAccount: 'Belum ada akaun?', signUpBtn: 'Daftar',
    featuresTab: 'Ciri-ciri', statsTab: 'Statistik', howToTab: 'Cara Guna', loginBtn: 'Log Masuk', heroBadge: 'Platform Rasmi Adtec Melaka',
    heroTitle: 'Dashboard Maklumat', heroSubtitle: 'Sistem pengurusan barang hilang & jumpa, maklumat kolej, dan komunikasi antara pelajar dalam satu platform yang moden dan selamat.',
    startNow: 'Mula Sekarang', learnMore: 'Ketahui Lebih',
    // Forgot Password keys
    forgotTitle: 'Lupa Kata Laluan', forgotDesc: 'Masukkan e-mel anda dan kami akan menghantar pautan untuk menetapkan semula kata laluan.', sendLinkBtn: 'Hantar Pautan', linkSentTitle: 'Pautan telah dihantar!', linkSentDesc: 'Sila semak peti masuk e-mel anda untuk arahan selanjutnya.', backToLoginBtn: 'Kembali ke Log Masuk',
    // Signup keys
    signupTitle: 'Cipta Akaun', signupDesc: 'Sertai rangkaian Adtec Melaka.', fullNameLabel: 'Nama Penuh', alreadyAccount: 'Sudah mempunyai akaun?', confirmPasswordLabel: 'Sahkan Kata Laluan', passwordMismatchError: 'Kata laluan tidak sepadan', backToHome: 'Kembali ke Laman Utama', passwordShortError: 'Kata laluan mestilah sekurang-kurangnya 8 aksara',
    // New keys
    staySignedIn: 'Kekal log masuk (Stay signed in)', loading: 'Memuatkan...', loginFailed: 'Log masuk gagal. Sila pastikan email dan kata laluan betul.',
    analyticsOverview: 'Gambaran Keseluruhan Analitik', monitorStats: 'Pantau statistik sistem anda secara langsung dari pangkalan data.', totalUsers: 'Jumlah Pengguna', totalReports: 'Jumlah Laporan', resolutionRate: 'Kadar Selesai', activeAccounts: 'Akaun Aktif', systemAuditLogs: 'Log Sistem Audit', adminActionRecords: 'Rekod tindakan pentadbir dan sistem.', exportLogs: 'Muat Turun Log', action: 'Tindakan (Action)', userEmail: 'E-mel Pengguna', time: 'Masa', noLogRecords: 'Tiada rekod log buat masa ini. (Sila tambah table \'audit_logs\')',
    noConversations: 'Tiada perbualan.', selectConversation: 'Pilih perbualan untuk mula mesej', online: 'Talian', reportUser: 'Lapor Pengguna', reportType: 'Jenis Laporan', spam: 'Spam', scammer: 'Scammer', inappropriate: 'Kandungan Tidak Sesuai', harassment: 'Gangguan', typeReason: 'Taip sebab...', submit: 'Hantar', send: 'Hantar', justNow: 'Baru sahaja',
    noInfoYet: 'Tiada pengumuman setakat ini.', noReportsYet: 'Tiada laporan barang hilang/jumpa setakat ini.', newReport: 'Laporan Baru:', noNewNotifications: 'Tiada notifikasi baru.',
    myProfile: 'Profil Saya', nameLabel: 'Nama', roleLabel: 'Peranan', memberSince: 'Ahli sejak', loadingReports: 'Sedang memuatkan laporan...', noReportsMade: 'Anda belum melaporkan sebarang item lagi.', saving: 'Sedang menyimpan...', messagingComingSoon: 'Sistem pemesejan dengan pemilik akan datang!',
    alertFillRequired: 'Sila isikan medan yang diwajibkan (Nama, Tarikh, Lokasi).', alertFillInfo: 'Sila isikan tarikh dan penerangan untuk maklumat ini.', defaultInfoTitle: 'Maklumat', defaultLocation: 'Umum', alertSuccessAdd: 'Berjaya ditambah!', alertFailedAdd: 'Gagal menambah data: ',
    badgeLost: 'Hilang', badgeFound: 'Jumpa', badgeInfo: 'Info', normalUser: 'Pengguna Biasa', today: 'Hari ini', messageFrom: 'Mesej dari', deleteBtn: 'Padam', cannotContactSelf: 'Anda tidak boleh menghubungi diri sendiri.', confirmResolveReport: 'Adakah anda pasti untuk menandakan laporan ini sebagai Selesai?', markResolved: 'Selesai',
    accountSuspended: 'Akaun anda telah digantung oleh Admin.',
    alertInvalidFile: 'Sila muat naik fail gambar sahaja.', alertFileSize: 'Saiz fail melebihi had 5MB.', alertSuccessDelete: 'Berjaya dipadam!', alertFailedDelete: 'Gagal memadam: ', confirmDelete: 'Adakah anda pasti mahu memadam item ini?', confirmDeleteUser: 'Adakah anda pasti mahu memadam pengguna ini?', alertFailedUpdateRole: 'Gagal mengemas kini peranan: ', alertFailedSuspend: 'Gagal menggantung/mengaktifkan pengguna: ', alertFailedUpdateStatus: 'Gagal mengemas kini status: ', alertSuccessReport: 'Laporan berjaya dihantar.', alertFailedReport: 'Gagal menghantar laporan: ', alertFailedUpload: 'Gagal memuat naik gambar: ', alertFailedSendMsg: 'Gagal menghantar mesej: ', alertOtpSent: 'Sila semak e-mel anda untuk kod OTP.',
    userManagementTitle: 'Pengurusan Pengguna', userManagementDesc: 'Urus pengguna berdaftar dan peranan mereka.', total: 'Jumlah', searchByName: 'Cari mengikut nama...', status: 'Status', actions: 'Tindakan', noUsersFound: 'Tiada pengguna dijumpai.', changeRole: 'Tukar Peranan', activate: 'Aktifkan', suspend: 'Gantung', reportManagementTitle: 'Pengurusan Laporan', reportManagementDesc: 'Luluskan, tolak, atau selesaikan laporan pengguna.', reportDetails: 'Butiran Laporan', noReportsFound: 'Tiada laporan dijumpai.', approve: 'Luluskan', reject: 'Tolak', resolve: 'Selesaikan', viewImage: 'Lihat Gambar', pending: 'Menunggu', approved: 'Diluluskan', rejected: 'Ditolak', resolved: 'Selesai',
    exportCsv: 'Eksport (CSV)', maintenanceMode: 'Mode Penyelenggaraan', maintenanceActive: 'AKTIF', maintenanceInactive: 'TIDAK AKTIF', maintenanceDesc: 'Jika diaktifkan, pengguna biasa tidak boleh log masuk ke dalam sistem sehingga ia dimatikan.', maintenanceTurnOn: 'Aktifkan (On)', maintenanceTurnOff: 'Matikan (Off)', confirmMaintenanceToggle: 'Adakah anda pasti untuk menukar status Maintenance Mode?', systemUnderMaintenance: 'Sistem Sedang Diselenggara', maintenanceReturnMsg: 'Kami sedang melakukan kerja-kerja penyelenggaraan untuk meningkatkan kualiti sistem. Sila kembali sebentar lagi. Segala kesulitan amat dikesali.', returnToLogin: 'Kembali ke Log Masuk', overlayWelcomeTitle: 'Selamat Kembali!', overlayWelcomeDesc: 'Untuk terus berhubung dengan kami, sila log masuk dengan maklumat peribadi anda.', overlayHelloTitle: 'Helo Pelajar Adtec!', overlayHelloDesc: 'Masukkan butiran peribadi anda dan mulakan perjalanan bersama kami.',
    uploadScreenshot: 'Muat naik Tangkapan Skrin / Bukti', screenshotNotice: 'Sila muat naik tangkapan skrin bukti supaya pentadbir dapat mengesahkan laporan dan mengelakkan penipuan.', viewProof: 'Lihat Bukti', noProofProvided: 'Tiada tangkapan skrin disertakan', proofModalTitle: 'Bukti Tangkapan Skrin Laporan', screenshotRequired: 'Sila muat naik bukti tangkapan skrin sebelum menghantar.',
    suspendModalTitle: 'Gantung Akaun Pengguna', suspendDurationLabel: 'Pilih Tempoh Penggantungan', dayCount1: '1 Hari', dayCount3: '3 Hari', dayCount7: '7 Hari', dayCount14: '14 Hari', dayCount30: '30 Hari', customDays: 'Hari Tersuai', indefinite: 'Kekal (Tanpa Had)', suspendedUntilDate: 'Digantung sehingga', confirmSuspendBtn: 'Gantung Akaun',
    logRoleChange: 'Menukar pangkat pengguna ({email}) kepada {role}',
    emailRoleChangeTitle: 'Peranan Akaun Dikemas Kini',
    emailRoleChangeMsg: 'Peranan akaun ADTEC Dashboard anda telah ditukar kepada {role} oleh pentadbir.',
    logUnsuspend: 'Mengaktifkan semula akaun pengguna ({email})',
    logSuspendDays: 'Menggantung akaun pengguna ({email}) selama {days} hari (sehingga {date})',
    logSuspendPermanent: 'Menggantung akaun pengguna ({email}) secara kekal',
    logDeleteUser: 'Memadam pengguna sepenuhnya ({email})',
    logReportStatus: 'Menukar status laporan ({email}) kepada {status}',
    emailAccountActivatedTitle: 'Akaun Diaktifkan Semula',
    emailAccountActivatedMsg: 'Berita baik! Akaun ADTEC Dashboard anda telah diaktifkan semula oleh pentadbir. Anda kini boleh log masuk seperti biasa.',
    emailAccountSuspendedTitle: 'Notis Penggantungan Akaun',
    emailAccountSuspendedMsg1: 'Akaun ADTEC Dashboard anda telah digantung oleh pentadbir atas sebab melanggar terma dan syarat. ',
    emailAccountSuspendedMsgDays: 'Akaun anda akan digantung selama {days} hari dan boleh diakses semula selepas {date}.',
    emailAccountSuspendedMsgPermanent: 'Akaun anda telah digantung secara KEKAL. Sila hubungi pihak pentadbiran jika ini adalah satu kesilapan.',
    notifReportStatusTitle: 'Status Laporan Dikemas Kini',
    notifReportStatusMsg: 'Laporan anda terhadap {name} kini berstatus: {status}.',
    emailReportStatusTitle: 'Status Laporan Anda Telah Dikemas Kini',
    emailReportStatusMsg: 'Laporan anda terhadap pengguna {name} telah disemak oleh Admin dan kini berstatus: {status}. Terima kasih kerana membantu komuniti ADTEC Melaka.',
    suspendPreviewPermanent: '🔒 Akaun akan digantung secara kekal sehingga diaktifkan semula secara manual.',
    suspendPreviewDays: '⏰ Akaun akan digantung sehingga: {date} (Sistem akan automatik unsuspend selepas tempoh tamat)', resetPasswordTitle: 'Set Kata Laluan Baharu', resetPasswordDesc: 'Sila masukkan kata laluan baru anda di bawah.', resetPasswordSuccess: 'Kata laluan berjaya ditukar! Anda kini boleh log masuk menggunakan kata laluan baharu anda.', newPasswordLabel: 'Kata Laluan Baharu', confirmNewPasswordLabel: 'Sahkan Kata Laluan', changePasswordBtn: 'Tukar Kata Laluan', invalidLink: 'Pautan tidak sah atau telah luput.', sessionNotFound: 'Sesi tidak dijumpai. Sila mohon pautan reset yang baru dari halaman log masuk.', resetFailed: 'Gagal menukar kata laluan. Sila cuba lagi.'
  }
};
